apiVersion: v1
kind: Pod
metadata:
  name: origin
  namespace: hubs
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: redis
    image: redis
    ports:
    - containerPort: 80
  - name: memcached
    image: memcached
    ports:
    - containerPort: 80
